
class EntryPoints:
    FLOW_START = 'FLOW_START_INTERVIEW_BEGIN'
    FLOW_END = 'FLOW_END_INTERVIEW_END'
    FLOW_CREATE_INTERVIEW_BEGIN = 'FLOW_CREATE_INTERVIEW_BEGIN' #Process Builder will split on '|' to 5 element lists, Flows = 4
    FLOW_CREATE_INTERVIEW_END = 'FLOW_CREATE_INTERVIEW_END'